const DB_GET_COLLECTION = require('./DB_GET_COLLECTION.js')
const DB_GET_DOC = require('./DB_GET_DOC.js')
const DB_DOC_SUBSCRIBE = require('./DB_DOC_SUBSCRIBE.js')
const DB_SET_DOC = require('./DB_SET_DOC.js')
const DB_ARRAY_UNION = require('./DB_ARRAY_UNION.js')
const DB_UPDATE_NESTED_VALUE = require('./DB_UPDATE_NESTED_VALUE.js')
const DB_DELETE_NESTED_VALUE = require('./DB_DELETE_NESTED_VALUE.js')
const DB_DELETE_DOC = require('./DB_DELETE_DOC.js')

module.exports = {
	GET_COLLECTION: DB_GET_COLLECTION,
	GET_DOC: DB_GET_DOC,
	DOC_SUBSCRIBE: DB_DOC_SUBSCRIBE,
	SET_DOC: DB_SET_DOC,
	ARRAY_UNION: DB_ARRAY_UNION,
	UPDATE_NESTED_VALUE: DB_UPDATE_NESTED_VALUE,
	DELETE_NESTED_VALUE: DB_DELETE_NESTED_VALUE,
	DELETE_DOC: DB_DELETE_DOC
}